let data = {
    book: [
        { type: '效率', des: '加快挖掘速度', level: 'V', o1: './img/附魔/工具.png', o2: './img/附魔/剪刀.png', hard: '10' },
        { type: '強力', des: '增加弓箭傷害', level: 'V', o1: './img/附魔/弓.png', hard: '10' },
        { type: '保護', des: '減少多數傷害', level: 'IV', o1: './img/附魔/裝備.png', hard: '10' },
        { type: '鋒利', des: '增加近戰攻擊傷害', level: 'V', o1: './img/附魔/鑽石劍.png', o2: './img/附魔/鑽石斧.png', hard: '10' },
        { type: '截肢剋星', des: '對截肢生物造成額外傷害', level: 'V', o1: './img/附魔/鑽石劍.png', o2: './img/附魔/鑽石斧.png', hard: '10' },
        { type: '輕盈', des: '節少跌落傷害', level: 'IV', o1: './img/附魔/鑽石靴子.png', hard: '5' },
        { type: '火焰保護', des: '減少火焰傷害', level: 'IV', o1: './img/附魔/裝備.png', hard: '5' },
        { type: '擊退', des: '增加擊退距離', level: 'II', o1: './img/附魔/鑽石劍.png', hard: '5' },
        { type: '忠誠', des: '三叉戟返回', level: 'III', o1: './img/附魔/三叉戟.png', hard: '5' },
        { type: '投射物保護', des: '減少來源於彈射物的傷害', level: 'IV', o1: './img/附魔/裝備.png', hard: '5' },
        { type: '不死剋星', des: '對不死生物造成額外傷害', level: 'V', o1: './img/附魔/鑽石劍.png', o2: './img/附魔/鑽石斧.png', hard: '5' },
        { type: '耐久', des: '減少物品減少耐久機率', level: 'III', o1: './img/附魔/裝備武器.png', o2: './img/附魔/耐久工具.png', hard: '10' },
        { type: '親水性', des: '加快水下挖掘速度', level: 'I', o1: './img/附魔/頭盔.png', hard: '10' },
        { type: '爆炸保護', des: '減少爆炸傷害', level: 'IV', o1: './img/附魔/裝備.png', hard: '2' },
        { type: '深海漫遊', des: '增加水下行走速度', level: 'III', o1: './img/附魔/鑽石靴子.png', hard: '2' },
        { type: '燃燒', des: '使目標著火', level: 'II', o1: './img/附魔/鑽石劍.png', hard: '2' },
        { type: '火焰', des: '箭矢使目標著火', level: 'I', o1: './img/附魔/弓.png', hard: '2' },
        { type: '幸運', des: '增加方塊掉落', level: 'III', o1: './img/附魔/工具.png', hard: '2' },
        { type: '冰霜行者', des: '允許水上行走', level: 'II', o1: '', o2: './img/附魔/鑽石靴子.png', hard: '2' },
        { type: '魚叉', des: '對水裡生物造成額外傷害', level: 'V', o1: './img/附魔/三叉戟.png', hard: '2' },
        { type: '掠奪', des: '生物能掉落更多物品', level: 'III', o1: './img/附魔/鑽石劍.png', hard: '2' },
        { type: '海洋的祝福', des: '提高釣魚獲得寶藏機率', level: 'III', o1: './img/附魔/釣竿.png', hard: '2' },
        { type: '魚餌', des: '提高魚咬鉤的速度', level: 'III', o1: './img/附魔/釣竿.png', hard: '2' },
        { type: '修補', des: '耗損經驗以修補工具耐久度', level: 'I', o1: '', o3: '	所有裝備武器工具', hard: '2' },
        { type: '衝擊', des: '增加弓箭擊退距離', level: 'II', o1: './img/附魔/弓.png', hard: '2' },
        { type: '水中呼吸', des: '延長水中呼吸時間', level: 'III', o1: './img/附魔/頭盔.png', hard: '2' },
        { type: '波濤', des: '將玩家向擲出三叉戟方向發射，僅在水中或雨中生效', level: 'III', o1: './img/附魔/三叉戟.png', hard: '2' },
        { type: '橫掃之刃', des: '增加橫掃攻擊傷害', level: 'III', o1: './img/附魔/鑽石劍.png', hard: '2' },
        { type: '喚雷', des: '在雨天召喚閃電攻擊生物', level: 'I', o1: './img/附魔/三叉戟.png', hard: '1' },
        { type: '無限', des: '射箭不會消耗普通箭矢', level: 'I', o1: './img/附魔/弓.png', hard: '1' },
        { type: '絲綢之觸', des: '被開採的方塊掉落本身', level: 'I', o1: './img/附魔/工具.png', hard: '1' },
        { type: '尖刺', des: '給予攻擊者傷害', level: 'I', o1: './img/附魔/鑽石胸甲.png', hard: '1' },
        { type: '分裂箭矢', des: '消耗一支箭可射出三支箭矢', level: 'I', o1: './img/附魔/弩.png', hard: '未知' },
        { type: '貫穿', des: '使箭矢穿過多個實體', level: 'IV', o1: './img/附魔/弩.png', hard: '未知' },
        { type: '快速上弦', des: '減少弩填裝時間', level: 'III', o1: './img/附魔/弩.png', hard: '未知' },
        { type: '消失詛咒', des: '物品會在玩家死亡時消失', level: 'I', o1: '', o3: '全裝備武器工具', hard: '1' },
        { type: '綁定詛咒', des: '物品無法被丟棄', level: 'I', o1: '', o3: '全裝備', hard: '1' },
    ],
}
new Vue({
    el: '#app',
    data: data
})